spring:
  datasource:
    url: jdbc:h2:mem:jobService;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    password: root
    driverClassName: org.h2.Driver
    username: system
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
