#spring:
#  datasource:
#    url: jdbc:h2:mem:jobService;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
#    password: root
#    driverClassName: org.h2.Driver
#    username: system
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    
server:
  port: 8020
#spring:
#  config:
#    import: configserver:http://localhost:8064
eureka:
  client:
     register-with-eureka: true
     fetch-registry: true
     service-url:
       defaultZone: http://localhost:8761/eureka/
       instance:
         hostname: localhost
    
#spring:
#  application:
#    name: JOB SERVICE
